/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CountUpData: typeof import('./src/components/CountUpData.vue')['default']
    ElText: typeof import('element-plus/es')['ElText']
    FadeChangeSwiper: typeof import('./src/components/FadeChangeSwiper.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LiveShotSwiper: typeof import('./src/components/LiveShotSwiper.vue')['default']
    NewsCard: typeof import('./src/components/NewsCard.vue')['default']
    NewsContent: typeof import('./src/components/NewsContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideTitie: typeof import('./src/components/SlideTitie.vue')['default']
    VerticalParallaxSwiper: typeof import('./src/components/VerticalParallaxSwiper.vue')['default']
  }
}
